language: 'python'

python:
  - '3.6'

services:
  - postgresql

addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-server-dev-9.6


install:
  - pip install -r requirements.txt
  - pip install coveralls

before-script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - python manage.py migrate

script:
  - coverage run --source=api manage.py test
  - coverage report
  - coveralls

after-success:
  - coveralls
